### ISSUE TITLE
error pop up needs an 'ok' button

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#10]
When the ugly yellowish error message comes up that says you did something wrong, we should have a button that says something like "OK, got it." that clears it away.  

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/10
- Originally reported by: [bgood](http://bitbucket.org/bgood)
- Originally created at: 2014-12-02T22:16:25.810

**Comment by JTFouquier** [comment]
@goodb, this is not a pop up. Do you still want the yellow error message to disappear from the webpage? ![Screen Shot 2015-07-20 at 4.10.19 PM.png](https://bitbucket.org/repo/y7oq9p/images/880785483-Screen%20Shot%202015-07-20%20at%204.10.19%20PM.png)  

I think it's nice to have the error message stay there until you do things correctly.  It's a harsh reminder to those making annotation mistakes :) 

----------------------------------------
Original comment by: [Jennifer Fouquier](http://bitbucket.org/JTFouquier)

**Comment by JTFouquier** [comment]
I haven't been in the UI meetings on mark2cure since January.  I'd trust your assessment and have you check in with Ginger if you are unsure.  

----------------------------------------
Original comment by: [bgood](http://bitbucket.org/bgood)

**Comment by x0xMaximus** [comment]
@gtsueng do we still want a dismiss "x" icon on these warning divs to clear away?

**Comment by x0xMaximus** [comment]
Current view:
![](http://i.imgur.com/7FqTY28.png)

@gtsueng just pinging to update again, what do we want to do with this?
