### ISSUE TITLE
Mark2Cure Mobile

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#100]
Mobile version of Mark2Cure that takes submitted annotations and further refines the classifications.  Can be like a mobile trivia game where an annotation (submitted by desktop Mark2Curator) is displayed and user is asked to further classify.
Eg- Disease Annotation: Congenital Disorders of Glycosylation is presented, and user is asked if this is a 'Disease name', 'Disease Class', 'Symptom', or 'Sign/Test Result?'

Additionally, Symptoms which are very noisy could be further refined with a game interface where list-like symptoms: (Eg- old-looking, wrinkled, inelastic skin) could be presented to a user and the user would be asked to come up with permutations of terms in this list under a given time. Eg- old-looking skin, wrinkled skin

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/100
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-05-01T18:02:14.816

**Comment by x0xMaximus** [comment]
@gtsueng  Did we want to close this as "Mark2Cure Mobile" is now implemented, so that we could transition this issue into a clearer discussion around the next task that would get implemented for concept sanitization?

**Comment by x0xMaximus** [comment]
Still open from July, with relationship implemented I'm going to close. If we would like to pursue this further, need more explicit details about what's requested in regards to mobile platforms
