### ISSUE TITLE
Fix points in training

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#102]
Currently each training gives 4000 points, and they don't appear to be cumulative until after you've reached the dashboard.

Points should also not be given for the training after it's been completed once.  Currently, if you use the url to repeat the training, you can accumulate a lot of points

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/102
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-05-05T23:40:41.113

**Comment by x0xMaximus** [comment]
~~Currently each training gives 4000 points, and they don't appear to be cumulative until after you've reached the dashboard.~~

**Comment by x0xMaximus** [comment]
~~Points should also not be given for the training after it's been completed once~~

From a database perspective, we've not preventing repetitive score records from being added. However, they're still able to do the on the site and will have the odometer animation, it is just that none of those cheated points will ever actually get added to that user now

**Comment by x0xMaximus** [comment]
@gtsueng was there anymore we wanted to do on this? I could add a UI alert that prevents this or could dynamically pull the starting value for the odometer or something. Everything from the backend is now hot on the server, but we don't have any UI that suggests that you're only awarded points once

**Comment by x0xMaximus** [comment]
@gtsueng can this be closed. If it's still an issue, could you detail out the specifics of what are being requested for change?
