### ISSUE TITLE
highlighting last word on a line bumps it to the next line

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#106]
long-known bug, but it becomes more annoying given multi-click selection...

before clicking:

![5-8-2015 12-01-37 PM.jpg](https://bitbucket.org/repo/y7oq9p/images/2791944644-5-8-2015%2012-01-37%20PM.jpg)

after clicking:

![5-8-2015 12-01-52 PM.jpg](https://bitbucket.org/repo/y7oq9p/images/878341192-5-8-2015%2012-01-52%20PM.jpg)

---
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/106
- Originally reported by: [Andrew Su](http://bitbucket.org/asu)
- Originally created at: 2015-05-08T21:04:24.009

**Comment by x0xMaximus** [comment]
Before anyone complains, the proposed fix does introduce a space when highlighting certain characters as shown:

![](http://i.imgur.com/zOz3uPe.png)

and I'd argue it's *good enough* for now as the pros outweighs this potential negative

//cc @AnoXDD

**Comment by AnoXDD** [comment]
Yeah I noticed this - but I thought these punctuations would be sanitized and de-highlighted when the user highlighted other words so I didn't think much of it.
