### ISSUE TITLE
Build doc loading interface

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#107]
Pending resolution of pubtator retrieval issues and some sort of grouped quest interface

allow admins to build groups, import docs, control pubtator.

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/107
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-05-14T19:03:28.302

**Comment by JTFouquier** [comment]
TODO: Expose this / abstract this interface so Admins can import PMID list and group name so I don't have to from command line for each new group.

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by JTFouquier** [comment]
Load next set of docs by Friday 05/29/2015.

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by JTFouquier** [comment]
Push for Prod. Addresses #107


→ <<cset f00d18d235be>>

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by x0xMaximus** [comment]
I'm bumping this up as this encompasses our need for a doc loading interface specific for different tasks.

**Comment by x0xMaximus** [comment]
Overridden by #194
