### ISSUE TITLE
Team Selection Interface

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#109]
Team selection interface that will appear in the user's editable profile settings page.

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/109
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-05-28T19:33:44.735

**Comment by JTFouquier** [comment]
Mock ups here: https://docs.google.com/presentation/d/1uBNlvxAUrMJLV_cKl3Ag2pP06Ae42NyMcA-cMzRlQ3I/edit#slide=id.g89195e771_0_135
Thoughts? Suggestions?

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by x0xMaximus** [comment]
I can select a team here, if further design is wanted or if changed experience (like being able to join multiple teams), then that should be resubmitted as a different issue

![](http://i.imgur.com/aLCsbnG.png)
