### ISSUE TITLE
Reduce spacing between title and abstract text

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#11]
Between the title and the abstract on:
http://mark2cure.org/training/intro/2/step/3/

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/11
- Originally reported by: [bgood](http://bitbucket.org/bgood)
- Originally created at: 2014-12-02T22:17:36.246

**Comment by JTFouquier** [comment]
this seems consistent across everything once the quests begin...

----------------------------------------
Original comment by: [bgood](http://bitbucket.org/bgood)

**Comment by JTFouquier** [comment]
Ah, its not a line break, just a giant space in between the divs.  See attachment.

----------------------------------------
Original comment by: [bgood](http://bitbucket.org/bgood)

**Comment by JTFouquier** [comment]
okay, updating the title, and changed from bug --> enhancement

----------------------------------------
Original comment by: [Andrew Su](http://bitbucket.org/asu)

**Comment by JTFouquier** [comment]
Hi @goodb!  Quests now look like this: 

![Screen Shot 2015-07-20 at 3.39.16 PM.png](https://bitbucket.org/repo/y7oq9p/images/3874542840-Screen%20Shot%202015-07-20%20at%203.39.16%20PM.png)

Should this issue be closed or updated?  Thanks!

----------------------------------------
Original comment by: [Jennifer Fouquier](http://bitbucket.org/JTFouquier)

**Comment by JTFouquier** [comment]
spacing actually seems larger between title and abstract in this version?  

----------------------------------------
Original comment by: [bgood](http://bitbucket.org/bgood)

**Comment by JTFouquier** [comment]
@goodb, Yes, yes it is. Haha. I just wasn't sure if the style was readdressed at some point and this title/abstract style won. 

----------------------------------------
Original comment by: [Jennifer Fouquier](http://bitbucket.org/JTFouquier)

**Comment by JTFouquier** [comment]
To me, it looks bad the way it is and I would still wish to make it a little more typical spacing.  But as I said in other issue comment, these kinds of design decisions are not currently my responsibility.  Please check in with Ginger or Andrew.  (or do what you think is sensible and issue a pull request)

----------------------------------------
Original comment by: [bgood](http://bitbucket.org/bgood)

**Comment by JTFouquier** [comment]
Cool.  Yes, I was just issue browsing.  Thanks!

----------------------------------------
Original comment by: [Jennifer Fouquier](http://bitbucket.org/JTFouquier)

**Comment by x0xMaximus** [comment]
This was addressed in a old commit and the way paragraphs are shown has been made uniform and constant.
