### ISSUE TITLE
Update user profile and team profile pages

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#112]
First assigned to Ginger to re-visit original designs, then assign to Max to implement

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/112
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-05-28T19:42:43.359

**Comment by JTFouquier** [comment]
User profile page display mock up: https://docs.google.com/presentation/d/13GkLxtuecAsed5BEd2_DnKw9sXz3yM6U8C0W1lretNU/edit#slide=id.g89195568d_0_6

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by JTFouquier** [comment]
Team profile page mock ups: https://docs.google.com/presentation/d/1T6q01xAQQrYCFBJ0tgvdfmK4PJQAhfE3jJbT5OginJ8/edit#slide=id.g5272c1567_0_37

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by JTFouquier** [comment]
@gtsueng any preference for the team urls?

mark2cure.org/team/TSRI for example?

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by JTFouquier** [comment]
team page: prioritize basic stats and team membership

user profile page: down-prioritize until we get badges

----------------------------------------
Original comment by: [Andrew Su](http://bitbucket.org/asu)

**Comment by JTFouquier** [comment]
Team formatting like mockup. Addresses #112


→ <<cset 80fd3922cc57>>

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by JTFouquier** [comment]
[init] Team App Integration. Addresses #112


→ <<cset 34d9d42af3f6>>

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by JTFouquier** [comment]
@gtsueng Just passing this back to you, the "Quick Stats" were implemented but am confused about the "Top Performer" metrics 

Additionally, I think it's worth playing with these designs to be "Group" focused instead of "Campaign" just b/c thats the categorization that we're really using and have to organize results by

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by x0xMaximus** [comment]
User profile with stats and team pages with stats exist, if further analytics about either are requested they should be detailed out in a new issue that explains what exactly is requested.
