### ISSUE TITLE
Empty annotations

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#124]
Calculated F-scores may be artificially lowered by the inclusion of empty annotations.  Somehow, there are annotations of length 0 which somehow have a type (and not just disease).  In the CDG doc set hash csv, there are 536 of these empty annotations. 

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/124
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-09-01T04:06:02.064

**Comment by gtsueng** [comment]
![empty annotations](https://cloud.githubusercontent.com/assets/9200138/16023033/b93fed68-316f-11e6-885d-c014b40eb51f.PNG)

**Comment by JTFouquier** [comment]
Empty annotations are a very repeatable issue caused by the grey highlight on misc. characters such as commas, slashes, and periods. You can click on those chars multiple times and they will submit an empty annotation for every click of the character.  Here you can see empty anns at 91, 100, and 107 representing the three misc. characters surrounding the word "gene." 


<img width="514" alt="screen shot 2016-06-13 at 2 22 19 pm" src="https://cloud.githubusercontent.com/assets/7920357/16023621/72d690ea-3172-11e6-9260-5a04b0b09252.png">
<img width="652" alt="screen shot 2016-06-13 at 2 22 50 pm" src="https://cloud.githubusercontent.com/assets/7920357/16023629/7bc325ba-3172-11e6-8764-f8c0b0c2e446.png">

**Comment by x0xMaximus** [comment]
Closes as 170c202 seems to have addressed this and I'm treating this as a submission bug. If the analysis is broken as a result of this, it should be addressed elsewhere
