### ISSUE TITLE
Single quote (apostrophe) highlight bug

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#125]
There seems to be an issue with highlighting terms enclosed by single quotes, in that the highlight will turn grey, and then cannot be further interacted with.  This issue has been reported multiple times.

Skyem: Bug - quest/368/4/: Another instance where punctuation prevents highlighting of the attached word. In this case: 'autoinflammatory 

Skyem: Same problem in quest/361/2/ for "holdase" and "unfoldase"

Tom: When I attempt to click on a term enclosed in single quotes I cannot change its color.

Skyem: Bug - Quest 161: Small bug in the second line. It won't accept highlighting on the word: 'congential ... I think because the apostrophe is there. It highlights gray instead and doesn't get submitted. (PMID: 22991164)

Skyem: Quest 174 - page 3. Text: ...is the first 'deafness-CDG ' . CDG should be... 
Because the first apostophe is directly next to the word it won't accept highlighting of the entire deafness-CDG and goes gray instead

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/125
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-09-02T17:30:23.417

**Comment by gtsueng** [comment]
the blue highlighting can be removed now compared to when it was grey before.
