### ISSUE TITLE
task feedback screen shows "New Annotation" instead of pairing with partner (was "New Annotation Bug")

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#126]
https://bitbucket.org/sulab/mark2cure/issues/126/new-annotation-bug

**Comment by JTFouquier** [comment]
Note: THIS ISSUE DID NOT MIGRATE CORRECTLY. For original issue see: https://bitbucket.org/sulab/mark2cure/issues/126/new-annotation-bug

gtsueng created an issue 2015-09-09
New Annotation bug. Even though the quest has been completed 10-11 times, user gets New Annotation feedback screen. Reported by Manabu Torii, for quest 22 in OGD. Docs in this quest include: 20299332, 11932895, 15039314, 21803123, 19365705
Views page indicates everyone has been partnered with"New Annotation for awhile...

Comments (10)


 gtsueng REPORTER
According to views page, everyone has been paired with "New Annotations" or GATTACA since around the time Mikulda1 did Q19 in the OST doc set...this dates to August 29, 2015 (according to the User-task relationships page).
2015-09-09

 Max Nanis
changed status to closed
Closes #126 >> pushing to PROD
→ <<cset 0422500667c3>>
2015-09-09

 gtsueng REPORTER:
This seems to still be happening. Two recent examples include Mariomar (working in the OST doc set morning of 9/16, which has been completed by at least 2 users), and Ckrypton in the mfold doc set (on quests I know she was the second one to complete).
2015-09-16

 gtsueng REPORTER
changed status to open
2015-09-16

 gtsueng REPORTER:
assigned issue to   Max Nanis
marked as minor
Not happening as much or as badly as before, but still happening.
2015-09-16

 Jennifer Fouquier:
gtsueng, Max Nanis: I did some testing on this and it looks like this line doesn't work. When you print "quest_relationship" on the line after, it will still print what was supposed to be filtered out via "exclude". This doesn't seem to be completely related to the "new anns" issue though, but it's a start.
Edit  Delete  2016-01-04

 Jennifer Fouquier:
changed status to resolved
fix select best opponent method
Error in sql code caused incorrect filtering. Improves and fixes issue #126
→ <<cset cb7999416522>>
Edit  Delete  2016-01-11

 gtsueng REPORTER:
changed status to open
Changed back to open
2016-01-11

 Jennifer Fouquier
Max Nanis: Ginger gtsueng and I were looking at this in detail on Friday and it looks like the "Views" get logged/saved in the DB with 0 annotations and it will default to "new anns".... (https://mark2cure.org/admin/document/view/). Is this the expected behavior to document each "view" that a user makes? It's a little bit confusing in the admin page. Also, there is no "date/time" column in the Views... a little hard to interpret. At some point can you briefly look into this, let us know why this is the behavior, and add the fix I made to the "filter" we can close this issue. Should be fast. Thanks!
Edit  Delete  2016-01-18

 Jennifer Fouquier
changed title to New Annotation bug
edited description

**Comment by x0xMaximus** [comment]
Unclear if still active or an issue, but will look into it

**Comment by gtsueng** [comment]
This bug appears to still be happening.  A user inadvertently reported that she missed getting the feedback. When asked for details, she confirmed that she was not getting the paired feedback screen.  Confirmed that she is not the only user to get the 'New annotation' feedback screen in spite at least 2-3 users having completed the same document. I got it too:
![new annotation but it s not](https://cloud.githubusercontent.com/assets/9200138/20501964/eb069518-aff0-11e6-9fe2-229eaab08907.PNG)

**Comment by gtsueng** [comment]
A user just reported seeing this bug again on Dec. 26, so the fix does not appear to have worked for everyone. 

"Keeps saying that I was the first person to annotate the documents in this set, when I'm fairly certain that's not the case." --https://mark2cure.org/talk/23816881/

**Comment by andrewsu** [comment]
likely relates to 405 error: (GET) Method not allowed (eg https://mark2cure.org/task/entity-recognition/606/3273/results.json)

![2017-01-20_13-49-31](https://cloud.githubusercontent.com/assets/2635409/22166734/61d9a2a2-df17-11e6-8806-c5570d15f164.png)

API calls `identify_annotations_results_bioc` and this line restricts to POST https://github.com/SuLab/mark2cure/blob/master/mark2cure/task/entity_recognition/views.py#L51

**Comment by AnoXDD** [comment]
Simply specifying the type and headers of the ajax request does not work. That will cause the server to return 500 error, so I guess Max has to look into this issue himself.

**Comment by AnoXDD** [comment]
@andrewsu If we also allows GET for `identify_annotations_results_bioc`, it will return the same error message as I commented above, but after some analysis on the existing code, I believe that error message was not actually an error, but something Max did to return a message from that method.
