### ISSUE TITLE
Enable BioC export of the user annotations for large groups

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#128]
Currently, BioC export of the user annotations works fine for small-medium doc sets: 
[https://mark2cure.org/api/group/4/user_annotations.xml](https://mark2cure.org/api/group/4/user_annotations.xml)

But crashes/times out for large doc sets:
[https://mark2cure.org/api/group/1/user_annotations.xml](https://mark2cure.org/api/group/1/user_annotations.xml)

Work around is to have Max generate .csv exports of the hash tables, but some means of exporting the data (without bugging Max) would be good.

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/128
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-09-17T18:33:21.060

**Comment by JTFouquier** [comment]
Philip said he would tackle this one.

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by JTFouquier** [comment]
@gtsueng already submitted a pull request for this one.

Also, here's the doc link on how it works : https://docs.google.com/document/d/1UoylxK4CV1qmJl4zj9yPyxz-BY47qWWMMgTvkuKomu0/edit?usp=sharing

Let me know of your thoughts in this, I'm particularly unsure of the terms I've used.

----------------------------------------
Original comment by: [Philip Vrieni Arguelles](http://bitbucket.org/pvarguelles)

**Comment by x0xMaximus** [comment]
Closed with work done for #129 

Done using s3 exports that are generated by bulk pubtator, er annotation, rel annotation and multi document and mutltiple task type BioC joining function
