### ISSUE TITLE
Automate periodic dumps of bioC output to S3

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#129]
large doc sets (eg CDG) time out with the bioC API endpoint.  To fix this problem, let's switch plans to a periodic dump of all user output from all doc sets in BioC format.

alternative solution: optimize the bioc API endpoint, but would need to make sure this was future-proof in case we get very large doc sets.  Let's discuss before we switch plans to this...

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/129
- Originally reported by: [Max Nanis](http://bitbucket.org/x0xMaximus)
- Originally created at: 2015-10-05T19:11:22.977

**Comment by x0xMaximus** [comment]
This has been implemented on a rudimentary level. More details on download page is expected and can be resubmitted as additional feature requests.
