### ISSUE TITLE
change leveling behavior

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#13]
Currently, users achieve levels as they progress through the training quests ("disease marking", "disease advanced", and "disease matching" I think).  

Per the discussion on hipchat, we should change such that a user has the "Trainee" level throughout the three training quests.  (We should then remove the "New skill acquired" line on the feedback page.)  After all training is done, user acquires level "Novice Magic Marker", and levels up according to the schedule in Ginger's google doc (column H): https://docs.google.com/spreadsheets/d/1wIKmuuiYg4xdc8AED7jU6vjLyBj9kUsNlFI3WGbbYeM/edit#gid=0

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/13
- Originally reported by: [Andrew Su](http://bitbucket.org/asu)
- Originally created at: 2014-12-02T22:36:12.530

**Comment by JTFouquier** [comment]
Updated the score/level cutoffs based on changes from 20 docs/quest to 5 docs/quest

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by x0xMaximus** [comment]
@gtsueng can we close this? Given:

- Our multi-task privilege development pipeline
- I believe the only place these titles are shown is when showing your partner in ER

**Comment by x0xMaximus** [comment]
Hasn't been updated or confirmed by @gtsueng – but given what this was originally requesting and how it's being handled now, I'm going to close it as it's been addressed through a separate issue that's already been completed (multi task training)
