### ISSUE TITLE
Translate html to jade (clarity/consistency)

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#135]
Jade is the preferred templating language of Mark2Cure because it is easier to read and less verbose than html. Although html can be pasted into jade templates in a rush, the html should be rewritten in jade style. 

Example:
https://github.com/SuLab/mark2cure/blob/master/mark2cure/task/relation/templates/relation/task.jade

This should be simple/quick fix.

**Comment by x0xMaximus** [comment]
Don't remember fixing this explicitly, but whatever HTML this was referring to is now gone
