### ISSUE TITLE
Highlighted titles strangeness

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#140]
A user has reported seeing entire titles highlighted twice. We've been unable to replicate this issue; however, another user submitted an example of this issue removing all other highlights but the strange title one:
![wth 02 highlighting](https://cloud.githubusercontent.com/assets/9200138/14794548/9036d63c-0ad9-11e6-9de9-5efe3128b141.PNG)

The following user clearly had the same pre-highlighted title, but chose to change some of the disease terms to treatment terms. Notice how the 3-NF has been changed to pink, but the surrounding parenthesis and spaces remained blue. If this is the case, then there will be a "( " will be a disease annotation
![wth 01 highlighting](https://cloud.githubusercontent.com/assets/9200138/14794601/cf1b6a48-0ad9-11e6-8f35-2ed49a6439f5.PNG)

The pubtator itself suggests that only a part of the title should have been highlighted
![19041363 pubtator title](https://cloud.githubusercontent.com/assets/9200138/14794760/50a78b6e-0ada-11e6-8432-5955b1808a97.PNG)

**Comment by gtsueng** [comment]
Looks like this issue might relate to the annotations out of thin air one. Looking at the annotations, it looks like the annotations for the title portion for these two users come out of nowhere as compared to the users where it seems to be correct. 
Eg- for first screenshot above, it looks like this:
![huh what 01](https://cloud.githubusercontent.com/assets/9200138/14798388/3c535bae-0aec-11e6-9aad-b847ecad31c2.PNG)
Notice that the first annotation for this title is 'mutations', which doesn't actually exist in the title text
Similarly, the second user has annotations out of nowhere saved as well
![huh what 02](https://cloud.githubusercontent.com/assets/9200138/14798448/7afa5a24-0aec-11e6-95e5-6a8cce6916ba.PNG)
But users without this issue seem to have the correct annotations:
![huh what 03](https://cloud.githubusercontent.com/assets/9200138/14798473/a15c7224-0aec-11e6-9746-426cd3e1805d.PNG)

**Comment by JTFouquier** [comment]
This was fixed with these commits 263cd7bedea9ec0cd299d7335668a66c3eb3cba7 and 79e795647703afd8d566992d229d4f18b7891bef  (pushed to home_scroll branch then merged to master)
