### ISSUE TITLE
Improve word cloud implementation & scaling improvements

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#142]
There is a known issue with the word cloud, referenced in the commit below that causes more commonly appearing words to be filtered out (not ideal!). I edited the scaling, but I'm not certain that this will solve the issue in every situation (i.e. if there is a larger quest completion difference between top and bottom contributors).   see: group/MATGS/

Also, the word cloud could be implemented in a more elegant/js way.  (see group_home.jade (remove form) and cloud.min.js).  

image below was from local/dev.
<img width="678" alt="screen shot 2016-05-05 at 9 05 16 am" src="https://cloud.githubusercontent.com/assets/7920357/15049690/9021a6d6-12a4-11e6-929e-4218c3eabd2d.png">

27f01f802a983c8e78ec877afe5822b5f364aed2

**Comment by x0xMaximus** [comment]
Is this still something we want on the group pages? I think this data could be presented in a table or more quantifiable way to show user contribution. Additionally, the design implementation of the current version doesn't match the brand of the site
