### ISSUE TITLE
Relationship training issues

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#144]
2 users reported getting stuck early on in the training. The looping issue was mentioned by 1 user prior to the wording changes

/1/step/3/
If user selects a nested relationship from the menu and then scrolls through the other potential choices, 
the popover instruction for how to proceed disappears.
Solution: disable relationship menu at this point in the training. It's not needed.

/1/step/5/
is fragile. If not done in a specific order, it breaks.
Examples:
relates to >> relates to >> relates to -- submit button appears
relates to >> any nested choice >> selection (to return) (returns to main menu with 'once again click..' popup (expected)>> relates to -- no submit button
relates to >> any concept >> selection (to return) >> relates to -- no submit button
has no relation ship to >> selection (even without instructions) >> relates to -- submit button pops up
cannot be determined >> selection (even without instructions) >> relates to -- submit button pops up

Once broken, following the original path, will not display the submit button (looping issue)

Training 2
2/step/1/
relates to >> treats >> Next 
Missing the appearance of Rule #2 

Training 3
3/step/1/
"Learn more about concept types here" link doesn't do anything (in firefox anyway)
Neither do the 'transcribe' and 'translate' links on https://mark2cure.org/training/relation/3/step/3/

Enhancements:
Try it out steps: would be nice if when users selected anything but the right answer, they get guidance that they selected the wrong answer so they
don't sit around thinking M2C is broken.

**Comment by JTFouquier** [comment]
For the links, @gtsueng @x0xMaximus, what do we want for transcription and translation... something like this? https://www.genome.gov/glossary/index.cfm?id=197... wasn't sure where we want to send them. Thanks!

**Comment by gtsueng** [comment]
The Wikipedia articles: 
https://en.wikipedia.org/wiki/Transcription_(genetics)
https://en.wikipedia.org/wiki/Translation_(biology)

**Comment by JTFouquier** [comment]
@gtsueng can you clarify this part: Training 2
2/step/1/
relates to >> treats >> Next 
Missing the appearance of Rule

I am confused.  Thanks!

**Comment by JTFouquier** [comment]
@x0xMaximus c.$el stuff for disabling things in the relation-training.js is confusing to me.  Can you fix "Solution: disable relationship menu at this point in the training. It's not needed." in part 1, step 3.  After that, this issue would be closed.

**Comment by gtsueng** [comment]
For : Training 3 - 3/step/1/
"Learn more about concept types here" link doesn't do anything (in firefox anyway)

I think this would be the easiest solution
![mock up for instructions](https://cloud.githubusercontent.com/assets/9200138/15302530/3be7178c-1b68-11e6-89a3-aae04146224c.PNG)
Then link the pop-ups Jennifer created before. Eg- 
![disease instructions](https://cloud.githubusercontent.com/assets/9200138/15302552/50848378-1b68-11e6-8682-cb51f007217c.PNG)

**Comment by JTFouquier** [comment]
@x0xMaximus can you please add these links?  They are modals and there is some sort of inheritance thing that is causing problems to add these. links are the relation modals here:  https://github.com/SuLab/mark2cure/blob/master/mark2cure/instructions/templates/instructions/drug-definitions-relation-modal.jade

**Comment by x0xMaximus** [comment]
I vote that once that user selects any concept (including Astrology) on [https://mark2cure.org/training/relation/1/step/3/](url) they're still allowed to cancel their selection. While this would let them unselect a correct answer, it doesn't support them proceeding until the correct answer is chosen again. This is how it behaves in the task and I don't see an incentive for training the users on a behavior that is slightly modified vs how it's actually implemented.

**Comment by gtsueng** [comment]
If the selector can't be disabled, then some sort of pop-up should be added to tell them to follow the instructions to the right, or just repeat the instructions on what they should be doing. If we don't provide any sort of feedback, users will just think the program is stuck or buggy, instead of figuring out the correct behavior. @JTFouquier can you apply the pop-up instructions logic from T2, T3 here as well? If people get it right, fine...they won't notice, but at least we don't give the impression that the program is broken for the people who get it wrong.
