### ISSUE TITLE
Disable left and center tree.js boxes in relationship training

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#146]
/relation/1/step/3/

Max can you do this?  based on static/js//tasks/relation-training.js#7  

I wasn't able to fix it.  Should be fast though. Thanks!

**Comment by x0xMaximus** [comment]
[https://mark2cure.org/training/relation/1/step/3/](url)

https://github.com/SuLab/mark2cure/blob/master/static/js/tasks/relation-training.js#L7

**Comment by JTFouquier** [comment]
This was fixed with purple popover logic instead of disabling part of the tree.js.  See file: https://github.com/SuLab/mark2cure/blob/master/mark2cure/training/templates/training/relation/part-1/page-3.jade
