### ISSUE TITLE
Relation training popover issue--parts 1-5 and 2-1

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#147]
When a user clicks the "select a relationship" field in the tree.js... the purple popover switches to the "once again" wording. This is unintentional due to the "back" event handling in the tree.js. Need to find a way to prevent this click from working if there is nothing displayed in the "select a relationship" field.

Relation training popover issue--parts 1-5 and 2-1

<img width="943" alt="screen shot 2016-05-16 at 1 40 12 pm" src="https://cloud.githubusercontent.com/assets/7920357/15303273/c77da628-1b6b-11e6-8ea7-41c5d1441ea4.png">

**Comment by x0xMaximus** [comment]
Note: I've been thinking about this for a while and not sure what to do, the "Once again" prefix that is added is technically after an user behavior event. So wether or not they intended to click on a button, they did and it appropriately shows an altered response. However, given that we can check for the current selection (it's empty) we could so a separate response all together

**Comment by x0xMaximus** [comment]
Honestly not sure what this is about anymore, but clearly a JS thing and I'll address it so labeling it as an actionable bug to deal with

**Comment by x0xMaximus** [comment]
Current URLS of this Issue:

- http://localhost:8000/training/relation/1/step/5/
- http://localhost:8000/training/relation/2/step/1/
