### ISSUE TITLE
More guiding help for users in relationship training 3.

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#149]
Apply the 'there's a better answer' logic for guiding users to the correct answer (as seen in training 2) to training 3, so that users who select the incorrect answer don't just think the code is broken and are encouraged to keep clicking.

Specifically, it can be used in these steps:
3/step/7/
3/step/8/
3/step/9/
3/step/15/
3/step/16/
3/step/17/
3/step/22/
3/step/23/
3/step/24/
3/step/25/

**Comment by JTFouquier** [comment]
Oh yes this is a fast fix @gtsueng. I thought we wanted to just do the popovers in the first steps

**Comment by JTFouquier** [comment]
@gtsueng do you still get these notifications? I'm showing people how we used Git for team-programming projects. Did this fix the issue? ;) Thank you!!! Can't wait to see you at the Su Lab 10 year in a few weeks!
