### ISSUE TITLE
Relation/Mobile: Next/submit location on training makes finding correct answer confusing

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#155]
The submit button and more importantly the purple popover guidance is in a bad location for the relationship *training*.  Either find a solution or insist that training be done only on desktop.  The users will not have any indication that the submit button OR popovers have appeared when they select the correct answer. This would be very confusing.  

I see this:

![screenshot_2016-05-19-16-22-42](https://cloud.githubusercontent.com/assets/7920357/15412708/87e31154-1dde-11e6-97fa-f820e367c67e.png)

Only when I scroll down I can see this:

![screenshot_2016-05-19-16-22-54](https://cloud.githubusercontent.com/assets/7920357/15412709/87e529a8-1dde-11e6-8568-7761df59ade0.png)

**Comment by JTFouquier** [comment]
@gtsueng this is an important thing to note.

**Comment by gtsueng** [comment]
@JTFouquier One potential solution is to put a popup when they select the correct answer for: https://mark2cure.org/training/relation/2/step/1/
https://mark2cure.org/training/relation/3/step/7/
To train them to scroll down to look for the submit button. The popup would be placed in the same place as the "there's a better answer, try again" one, but would say "Correct, click 'submit' at the bottom of this page," for the first instance where it's needed (relation/3/step/1/)
and "Remember, the submit button appears at the bottom when the correct answer is selected in the tutorials"
