### ISSUE TITLE
Mobile: Text in relation app is too large

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#156]
Text is often hanging off the box. Although this seems like a quick fix, I wasn't sure if we should make it change in size via bootstrap or something so that it doesn't change size on desktop. It looks nice in desktop. 

![screenshot_2016-05-19-16-22-42](https://cloud.githubusercontent.com/assets/7920357/15412743/dcbb9138-1dde-11e6-803c-9ec4b872f2b4.png)

**Comment by gtsueng** [comment]
Tested it on an iphone5 and a Nokia Windows phone. They both look fine.
Windows: ![fot39ae](https://cloud.githubusercontent.com/assets/9200138/15416653/a018ba16-1e02-11e6-8059-f27fb843237e.png)
iphone5: 
![img_4758](https://cloud.githubusercontent.com/assets/9200138/15416671/d1681b48-1e02-11e6-92bd-34a7ea16eab6.PNG)
Will test on an android in a bit.

**Comment by gtsueng** [comment]
Screencap from an android phone: 
![screenshot_2016-05-19-20-54-50](https://cloud.githubusercontent.com/assets/9200138/15416830/528af848-1e04-11e6-834d-631cc01a1441.png)

**Comment by JTFouquier** [comment]
Did you get to the parts where there are purple popovers?  The reason I started using my phone horizontally was because when I was vertical the popovers blocked the text making it confusing.

**Comment by x0xMaximus** [comment]
@gtsueng just checking, can this be closed?
