### ISSUE TITLE
Users report there needs to be more explanation about incorrect concept reporting

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#159]
http://mark2cure.org/training/relation/1/step/3/

This is a little bit confusing.  The purple popover alone is not enough to indicate what they are really doing here.

**Comment by gtsueng** [comment]
I suspect that this may be due to attention to the purple popover text, negating attention to the text about incorrect concept selection by the computer.

**Comment by x0xMaximus** [comment]
Unclear if there is an actionable here, the pull request addressed this so I am closing it
