### ISSUE TITLE
Improve wording on relationship training start page

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#166]
Brainstorm ways to make the relationship training a bit more clear/obvious/interesting/exciting.  When users are throw into it, it's a little unclear as to what is going on. Not sure the best approach to this but it's definitely something to consider.

**Comment by JTFouquier** [comment]
Continued discussion: When showing them the home screen they mentioned that the main call to action "get started" is pretty enticing. So once you click on it, let's say it takes you to the relation app (especially if you are on mobile and auto redirected), then it's almost like you need an example or something to get them started. Also it mentions the 'concept recognition task', but at this point the users aren't even aware of what that is. This was pretty confusing to our testers today.

**Comment by gtsueng** [comment]
This is an easy one. Just get rid of everything prior to "Learn how to use the relationship extraction tool to annotate the relationship between different concepts in biomedical text."  That text about concepts was there before because our initial examples started with actual biomedical concepts. Now it doesn't.

**Comment by JTFouquier** [comment]
Great. Yes that pull request looks like it will make things more clear.  Do you think we also might want to include our "about" page link at the start of the relation training (and the ER for that matter)? Their impression was that it's very tempting to just click "get started" and then they didn't have much background about the website. Just ideas here.
