### ISSUE TITLE
"EXPAND" button does not work on relation module (on mobile/small screens)

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#167]
I am guessing that this is because the only thing in the header, other than the title, is the logo.  

@x0xMaximus do you have any other plans for this header or should I just remove the "expand" button if the users are not logged in?

**Comment by JTFouquier** [comment]
This is kind of related. On a small or medium size screen when you are on the talk page or other pages, the dashboard/m2c logo disappears from the header, and you can't return to the dashboard unless you go to the right url or you resize your browser window. 

![screen shot 2016-06-15 at 3 11 37 pm](https://cloud.githubusercontent.com/assets/7920357/16099147/89aa6d6a-330b-11e6-9d56-0c6f244d5ad6.png)

**Comment by x0xMaximus** [comment]
This is being addressed in the big changes per 6569df9b90ab112bbe20315007530946f1276785 – not forgotten about but will fall together with Bootstrap changes

**Comment by x0xMaximus** [comment]
@gtsueng just checking, can this be closed?
