### ISSUE TITLE
Relationship feedback is confusing

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#169]
![feedback not displaying properly](https://cloud.githubusercontent.com/assets/9200138/15510306/b1fcc074-218b-11e6-991d-56bcc8bf03c8.PNG)

**Comment by gtsueng** [comment]
![feedback not displaying properly](https://cloud.githubusercontent.com/assets/9200138/15511337/f92b5894-218f-11e6-9540-c487de052fa1.PNG)
Maximum on x-axis should reflect the number of submitted relationships, and selections should be scaled accordingly.

**Comment by x0xMaximus** [comment]
![do this](http://i.imgur.com/79MBEFl.png)
