### ISSUE TITLE
Relationship module: Highlighting in text frequently missing

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#170]
The pubtator coverage of the Alacrima doc set is 94%, yet the majority of the docs I've clicked on so far in the relationship module are missing highlighting in the text, or only have partial highlighting.
![highlighting fail](https://cloud.githubusercontent.com/assets/9200138/15510470/3fd8c1b8-218c-11e6-971b-747f461f6462.PNG)

**Comment by JTFouquier** [comment]
@x0xMaximus, As far as testing I was using this pmid: 11353896, http://mark2cure.org/task/relation/1572/ 

There are annotations in the pubtator that are missing in the text (search for 11353896) : 
https://mark2cure.org/api/group/3/pubtator_annotations.json

Gene UID 5443 is the same as the one in the title that does display. 


![screen shot 2016-05-24 at 5 20 24 pm](https://cloud.githubusercontent.com/assets/7920357/15524111/43b03990-21d4-11e6-9c59-aca8189a0e8f.png)
![screen shot 2016-05-24 at 5 18 20 pm](https://cloud.githubusercontent.com/assets/7920357/15524110/43b04a5c-21d4-11e6-9fc4-52a14a70eaf9.png)

Below, you can see that in passage 0 the annotation is there, but in passage 1 the annotation is **null**. Do you know how to fix this?  This is likely the issue!  :)  
![screen shot 2016-05-24 at 5 22 28 pm](https://cloud.githubusercontent.com/assets/7920357/15524109/43afbc04-21d4-11e6-856f-31443a659abc.png)
