### ISSUE TITLE
Highlighting is missing for some docs despite having successful pubtators (reln app)

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#173]
example 1:
https://mark2cure.org/task/relation/1528/

These are two examples where the pubtator for these alacrama group docs loaded correctly, but the annotation AAAS is missing from https://mark2cure.org/api/group/3/pubtator_annotations.json, while progressive debilitating disorder is there, but it is not being highlighted. 
![screen shot 2016-05-27 at 9 41 04 am](https://cloud.githubusercontent.com/assets/7920357/15614719/28d5c942-23ef-11e6-8257-21746a95ad54.png)

example 2:
disorderhttps://mark2cure.org/task/relation/1524/

**Comment by gtsueng** [comment]
A possible clue. It looks like the first load of the doc is missing highlights, but if I load the doc again after submitting relationship anns...it's highlighted.
First time viewing the doc (no highlights):
![no highlights](https://cloud.githubusercontent.com/assets/9200138/15723105/c1a5c7d0-27f5-11e6-8f48-8ad554929ec5.PNG)
After completing the doc and visiting it again from my dashboard:
![after completing the doc](https://cloud.githubusercontent.com/assets/9200138/15723118/cf96aabc-27f5-11e6-8ce8-4f4f28d91feb.PNG)

**Comment by gtsueng** [comment]
Some relationships that seem to have this problem: 1499, 1539, 1504

**Comment by JTFouquier** [comment]
@x0xMaximus @gtsueng I'm having a hard time reproducing this issue because it's behaving fine in my local server as you can see below (tested the three examples Ginger provided and they were fine on initial loading). This makes testing very challenging.  Max, any thoughts as to why the behavior for highlighting is different on dev vs prod?  Thanks!
<img width="829" alt="screen shot 2016-06-01 at 4 02 07 pm" src="https://cloud.githubusercontent.com/assets/7920357/15728905/6cbdabb0-2814-11e6-9d46-7754d4febd69.png">

**Comment by JTFouquier** [comment]
These are ones I am having issues with @x0xMaximus 1504, 1512 refresh, 1514, 1524, 1499, 1529 refresh, 1531

Safari Version 8.0.7 (10600.7.12):
Chrome Version 51.0.2704.84 (64-bit)

Login, then go to direct link; no answers.

https://mark2cure.org/task/relation/1504/

safari incognito WORKS
safari regular FAILS, WORKS on refresh
chrome incognito FAILS, WORKS on refresh
chrome regular FAILS, FAILS on refresh


https://mark2cure.org/task/relation/1514/

safari incognito WORKS
safari regular FAILS, WORKS on refresh
chrome incognito FAILS, WORKS on refresh
chrome regular FAILS, FAILS on refresh

**Comment by x0xMaximus** [comment]
This is has nothing to do with a user's browser.

This issue occurs in regards to 2 specific endpoints:

- A: https://mark2cure.org/document/pubtator-new/<document__document_id>.json
- B: https://mark2cure.org/task/relation/<document_id>/api/

Endpoint A is used to fetch the annotations for the document, it serves the JSON version of the bioc document with the annotations.

Endpoint B is used to fetch the relationship tasks that will be used for comparison. It gives us the oder of the documents and the comparisons to perform between them.

Annotations do not work when Endpoint B finishes before the network request for Endpoint A finishes.

**Comment by gtsueng** [comment]
Not seeing it anymore, closing the issue
