### ISSUE TITLE
relation feedback is not working properly

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#174]
Reported by user and can readily be replicated. The feedback screen seems to match the first relationship annotation submitted, and is incorrectly applied to all subsequent relationship annotations.
In this example, the first pair was cortisone and cardiac dilation. I marked cardiac dilation as incorrectly identified by the algorithm. Feedback for the subsequent pair (dysphagia and cortisone) is as follows:
![feedback displaying improperly](https://cloud.githubusercontent.com/assets/9200138/15682034/a5ce9630-2710-11e6-89e2-22b6852e0ea2.PNG)
You can see how dysphagia and cortisone are highlighted in the text, but the feedback suggests that it was for the cardiac dilation/cortisone pair.
Subsequent pair (Allgrove's and cortisone) had the same issue:
![feedback displaying improperly 2](https://cloud.githubusercontent.com/assets/9200138/15682091/e36284b6-2710-11e6-9baf-151b995a1488.PNG)

**Comment by gtsueng** [comment]
Additionally, the distribution of the selected answers can add up to be over 100% as seen in this example:
![greater than 100](https://cloud.githubusercontent.com/assets/9200138/15682378/3c5995cc-2712-11e6-87d0-613482fc86cb.PNG)

**Comment by JTFouquier** [comment]
@x0xMaximus, Can you look into the percentage issue? I have confirmed that the values in the relation feedback-api are correct, but the calculation is not working and causing values > 100%.  I'm not sure why though... the calcs look good to me. Perhaps something is wrong with the data filter or max value. The problem appears to be here https://github.com/SuLab/mark2cure/blob/master/static/js/tasks/relation.js#L214

**Comment by gtsueng** [comment]
Commit seems to have worked in resolving both issues.
