### ISSUE TITLE
Completed Relationships in the dashboard

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#175]
I thought that relationship quests that I complete would be removed from my dashboard. That doesn't appear to be the case, and a user can re-enter the document they just completed. When submitting a doc they've done before, it will either give this:
![dashboard refresh slow](https://cloud.githubusercontent.com/assets/9200138/15723202/4092ab62-27f6-11e6-987c-4951e735a6b2.PNG)
Which is fine. Problem is when it gives this instead:
![trying to do a doc from dashboard](https://cloud.githubusercontent.com/assets/9200138/15723222/57f9f88c-27f6-11e6-8879-83b927f07e12.PNG)
Fix filter to remove the docs that user has completed so the user doesn't try to do them again by accident.

**Comment by JTFouquier** [comment]
Looks like the docs are disappearing once you refresh.  This was confirmed by myself and @gtsueng. Essentially it throws you back so fast after the relation doc completion, that the dashboard is incorrect initially, but when you reload it seems fine.

**Comment by gtsueng** [comment]
Users can continue to do the community-completed relation docs. There are some on the dashboard that are well over 160% complete.

**Comment by gtsueng** [comment]
Not sure what's going on, but a user reported experiencing this issue 2 days ago.  Re-opening it so I can keep an eye out for it. Screenshot sent by user: http://prnt.sc/d9f1fs

**Comment by gtsueng** [comment]
This may be related to an issue raised by one of our users: 
"In the relational database list, I have two items left: (1) ACTH Resistance Syndromes, and (2) Familial occurrence of Adrenocortical Insufficiency… Neither of these will open and I cannot get rid of them. "

Opening the resulting item will give this screen
![task 1460](https://cloud.githubusercontent.com/assets/9200138/20765005/7a60f01e-b6e5-11e6-9753-3e940f386b19.PNG)

**Comment by x0xMaximus** [comment]
Force complete stated views for users who never completed RE Doc but were done by the community prior to completion. 

Viewing will toggle complete bool for removing only after Tree library notices response is len==0
