### ISSUE TITLE
Highlighting sometimes only appears after refreshing page (relation app)

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#176]
This is different behavior than the docs that are not displaying highlighting at all. These are a few examples of pages that are missing highlights upon first load, but highlights appear after refresh. This was confirmed this morning by @gtsueng and myself. 

https://mark2cure.org/task/relation/1569/
https://mark2cure.org/task/relation/1527/
https://mark2cure.org/task/relation/1488/
https://mark2cure.org/task/relation/1433/

**Comment by gtsueng** [comment]
Confirmed that the highlights for the first one are not there on first load, but appear on refresh. Subsequent docs appeared to have the highlights on first load (maybe because I refreshed the first one before loading the subsequent docs).

**Comment by JTFouquier** [comment]
Mine are all appearing except for the second one now. This issue appears to be very sporadic. 
<img width="1229" alt="screen shot 2016-06-02 at 9 28 06 am" src="https://cloud.githubusercontent.com/assets/7920357/15752765/651e2dea-28a4-11e6-9cbf-cd598aabb377.png">

**Comment by JTFouquier** [comment]
Yes, definitely sporadic. This one also did it again. 
<img width="1185" alt="screen shot 2016-06-02 at 9 32 46 am" src="https://cloud.githubusercontent.com/assets/7920357/15752888/0cf20c1c-28a5-11e6-9073-97afa8131471.png">
