### ISSUE TITLE
Anonymous header with "log in" and "sign up" are missing

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#180]
When users are not logged in, there should be an option in the header for them to "sign up" or log in"...  this was somehow deleted after I worked on the group home page at some point. @gtsueng those were the only two features we wanted on the anonymous header right?  @x0xMaximus I know the styling wasn't perfect, but simple text is fine for now. Just important for users to easily log in or sign up and start Mark2Cure. 

https://mark2cure.org/group/HSPT1/
https://github.com/SuLab/mark2cure/blob/master/mark2cure/common/templates/common/group_home.jade

**Comment by x0xMaximus** [comment]
I'm not sure a "Sign up" button is appropriate. Shouldn't this behavior be exclusive to the landing page, using the "Get Started" language? I don't think we use Sign up anywhere else on the site so it would be confusing. @gtsueng  thoughts? For now, if you view a page that uses the basic header and you're not authenticated, it will provide a active link to the login page, this seems to suggest that the login page should have the following copy of some sorts: "Don't have account, click to Get Started!"

Technically this is addressed using cb2f687 but will have to be overhauled anyway given the updates to bootstrap, via 6569df9b90ab112bbe20315007530946f1276785

**Comment by gtsueng** [comment]
Agree that login pages typically have mechanisms for getting registered, so text along the lines of "Don't have account? Get started now" would make sense on the login page. That said, we could lose users who don't know to look there to register. Easy fix may be to add a 'get started' link under the 'login' in the header, since we don't really use the term 'sign up' anywhere.

**Comment by x0xMaximus** [comment]
Added Get Started to header: ![](http://i.imgur.com/NHCIueM.png) – TBH I think this is silly b/c most of the time the "Get Started" link is one the instruction pages, and that would only kick them back to Page1 of the ER or Relation training


Added the copy to the login page: ![](http://i.imgur.com/3VBUxov.png)

**Comment by gtsueng** [comment]
Agree it's silly for the first 5 or so training pages (prior to login), but makes perfect sense for the growing number of mission-specific (group) pages we have.
