### ISSUE TITLE
Pointer hover changes behavior/bounces in relation app (extremely low priority)

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#181]
_This is extremely minor_ although if a quick fix would change it that'd be nice but I imagine it's a bit more tricky and has to do with YPET. 

Essentially when you hover over the title and abstract, the "disable" pointer for the mouse changes back and forth which is a little distracting and annoying. 

![2016-06-08 11 04 59](https://cloud.githubusercontent.com/assets/7920357/15905320/4fa6fca2-2d69-11e6-8da6-b8431eae3804.jpg)
![2016-06-08 11 04 17](https://cloud.githubusercontent.com/assets/7920357/15905319/4f9acbee-2d69-11e6-9920-f82ad382217d.jpg)
![2016-06-08 11 03 56](https://cloud.githubusercontent.com/assets/7920357/15905318/4f99e2ba-2d69-11e6-8b10-738e9836a257.jpg)

**Comment by x0xMaximus** [comment]
While is probably the desired behavior, it's important to note that now when reviewing completed ER documents, on the Talk Page for example, or active Relation tasks, the user is compeletly unable from being able to copy text b/c they're no longer able to make a selection. The ability to copy text from these abstracts, for relation tasks or reviewing ER work,might be important to our users. @gtsueng thoughts on this?

**Comment by gtsueng** [comment]
I think it's fine to have selection completely disabled within the box (which is what I assume your fix did) for the relationship app. I worry that facilitating their look up of things in the relationship app (w/ copy/paste features) will encourage them to draw the relationship inferences from other sources. If they really want to look something up, they can always type it in. So far, we haven't heard from users who really desire this feature outside of the actual ER task.
