### ISSUE TITLE
In tree.js, the "incorrect concept button" should be disabled after user selection

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#182]
Red makes sense here because the user can click to report the wrong concept.
<img width="1194" alt="screen shot 2016-06-08 at 4 08 04 pm" src="https://cloud.githubusercontent.com/assets/7920357/15914160/69fd71e2-2d93-11e6-8e14-8f62627074d1.png">

Here, "autonomic neuropathy" is already selected, but the user can still click on the red "incorrect concept"... 
<img width="1223" alt="screen shot 2016-06-08 at 4 08 22 pm" src="https://cloud.githubusercontent.com/assets/7920357/15914159/69f4f8c8-2d93-11e6-82fe-0cac2628ab6d.png">

Consider making it obvious for the user that they already selected this term, by having some action occur in the tree... at one point I didn't realize I already clicked on the incorrect concept and kept clicking it, but because there was no "action/change" in the tree, I didn't realize it was already displayed in the center of the tree.

**Comment by x0xMaximus** [comment]
Added the behavior to allow the Concept selection to remain red if selected so as to prevent confusion about if it's currently selected. @gtsueng do we think this is a good solution to resolve this, by keeping it red during an incorrect selection, or should additional ui behaviors supplement it?

**Comment by gtsueng** [comment]
I think leaving it red is an acceptable solution to the problem.
