### ISSUE TITLE
Resizing header causes the mar2cure logo/dashboard link to disappear

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#185]
This issue affects the users' ability to return to the dashboard and keep working. Fix to make it easier for users to keep going. 

**Dashboard link okay:**
<img width="880" alt="screen shot 2016-06-21 at 11 23 00 am" src="https://cloud.githubusercontent.com/assets/7920357/16241477/b36a8ffe-37a2-11e6-843a-c26ee6e5d2f0.png">

**Dashboard link disappears when resizing (likely a bootstrap issue):**
<img width="784" alt="screen shot 2016-06-21 at 11 23 09 am" src="https://cloud.githubusercontent.com/assets/7920357/16241476/b3687af2-37a2-11e6-988f-f74dd72fc435.png">

**Comment by x0xMaximus** [comment]
Will finish properly with update of Bootstrap 4 as the final version approaches. Addressed heavily in commit 6569df9b90ab112bbe20315007530946f1276785 but need to hold off as it's far too big a project to undertake just for this.

**Comment by x0xMaximus** [comment]
@gtsueng just checking, can this be closed?

**Comment by gtsueng** [comment]
Checked it on an iphone, windows, and android. Seems to be fine
