### ISSUE TITLE
Relationship feedback synopsis is confusing

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#189]
The text for the two concepts displayed may be synonymous to what was actually shown to the users, but it doesn't appear in the text.  

Eg. For this doc: http://www.ncbi.nlm.nih.gov/pubmed/21565631
(BTW- the link to pubmed from that very same page works great)

The concepts shown are 'ALADIN' and various synonyms of the diseases that are actually in the text.  However, unless you know that AAAS gene (shown in text) is ALADIN (displayed in feedback(, this will be confusing.  Additionally, Achalasia of Cardia (displayed in feedback) is shown instead of Achalasia (shown in text).

Picture of synopsis view of feedback from this doc.
![synonym not the same almost looks like a different doc](https://cloud.githubusercontent.com/assets/9200138/16528222/56e73f0e-3f70-11e6-86fd-7a3754942404.PNG)

**Comment by x0xMaximus** [comment]
@gtsueng Is there a desired actionable on this? What is a proposed change? I see a few options:

- Only show the specific word exactly that the user was presented (this would require we address the details of concept <<>> text selection more specificly and develop a smarter way to do this selection)
- Show the all optional words / text for the specific concept

**Comment by gtsueng** [comment]
How is the display being handled when it's being presented to the user for relationship extraction? Can the same strategy be employed for the text selection of the concept?

**Comment by gtsueng** [comment]
![wrong concept feedback](https://cloud.githubusercontent.com/assets/9200138/16746552/ac45f574-476f-11e6-8eed-4f78db6df861.PNG)
It's a really hard leap to make to go from 'decrease of retinal nerve fiber' (abstract text) to 'hyperreflexia' (feedback text)

**Comment by x0xMaximus** [comment]
I approached this solution via method 1. We're now doing a better job of making sure the concept text that was used for that concept is the same across all apis / MySQL. It's now pulled on production so you can start to test it

**Comment by gtsueng** [comment]
From my tests, it looks like the fix has resolved the problem.
