### ISSUE TITLE
Bracket characters ("[") appear in abstract titles

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#190]
Very minor issue, but possibly filter the bracket out or make "white or clear" or something, so as to not mess up the offsets.  

It would look better if it doesn't show up in the document list on the community home page or when working on the task. 

**Community Dashboard:**

<img width="534" alt="screen shot 2016-09-03 at 9 26 34 am" src="https://cloud.githubusercontent.com/assets/7920357/18225769/b5cd2644-71b8-11e6-9fa5-a72b41c4e7df.png">

**Task:**

<img width="1132" alt="screen shot 2016-09-03 at 9 26 47 am" src="https://cloud.githubusercontent.com/assets/7920357/18225770/b5ceb32e-71b8-11e6-8f69-b42b21db0c8b.png">

**Comment by x0xMaximus** [comment]
Is this something we want? The original titles have brackets and I don't believe we should be in the business of rewrite document titles. I'm suggested this is closed without any actions.

Example: https://www.ncbi.nlm.nih.gov/pubmed/17880786

**Comment by x0xMaximus** [comment]
Closing after agreed consensus.
