### ISSUE TITLE
Add M2C blog on site

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#197]
This will allow for SEO to directly link M2C content to M2C, instead of sending it to sulab.org, also allows for more opportunities for SEO.

**Comment by andrewsu** [comment]
suggested simple implementation:

- create a micro or small AWS instance
- install wordpress (or create directly with this [AMI](https://aws.amazon.com/marketplace/pp/B00NN8Y43U?qid=1477688986932&sr=0-1&ref_=srh_res_product_title) )
- migrate all M2C posts from sulab.org/blog
- create dns for blog.mark2cure.org.

**Comment by gtsueng** [comment]
New blog set up. 

Not yet done:
-Create/Add/Integrate disqus (Ghost blogging platform has no commenting system by default)
-Edit SEO for each post
