### ISSUE TITLE
Encouraging Message for empty networks

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#203]
The 'toggle network' for any group that doesn't have docs completed by 15 users will display as empty.  Would be good to pop up a message, "Network not yet available, help uncover the nodes by completing a quest! Only completed quests will appear in the network."

**Comment by x0xMaximus** [comment]
https://sentry.io/su-lab/mark2cure_prod/issues/179665162/

**Comment by JTFouquier** [comment]
@gtsueng, let me know if this is what you were thinking. Allows toggling for groups with a network, and makes the popup (over and over) if there isn't a network to see. 

<img width="972" alt="screen shot 2016-11-29 at 2 18 10 pm" src="https://cloud.githubusercontent.com/assets/7920357/20729563/ccce5108-b63f-11e6-8884-3b151931cd0e.png">
<img width="875" alt="screen shot 2016-11-29 at 2 17 32 pm" src="https://cloud.githubusercontent.com/assets/7920357/20729564/cce74a6e-b63f-11e6-8e3a-8ab4cbc51b7c.png">

**Comment by gtsueng** [comment]
@JTFouquier Yes, this is what I had in mind!

**Comment by x0xMaximus** [comment]
Ooops, got 205 and 203 mixed up. 8874320d14f4a4d9f5ee37f2be167d5bc67d428f addresses this

**Comment by x0xMaximus** [comment]
Addressed in outreach to Sigma team https://github.com/jacomyal/sigma.js/issues/802
