### ISSUE TITLE
New relationship tasks dashboard not behaving as expected

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#206]
For some users, the waterfall is running dry, which means they are unable to contribute further.

One user reported being able to see the newly loaded docs
Another user reported not being able to see the newly loaded docs: 
"In the relational database list, I have two items left: (1) ACTH Resistance Syndromes, and (2) Familial occurrence of Adrenocortical Insufficiency… Neither of these will open and I cannot get rid of them. Can you help? Also, your new RDB (relation database) items do not show on my list (you were asking J and I about this the other day)."

As seen in this cap of GATTACA's dashboard, the newly loaded docs are not appearing in the dashboard.
![waterfall broken](https://cloud.githubusercontent.com/assets/9200138/20764735/64447efa-b6e4-11e6-9c8e-90b8852e471f.PNG)
The docs here are what's left from the Alacrima doc set.

**Comment by x0xMaximus** [comment]
@andrewsu + @gtsueng the current logic is as follows:

```sql

SELECT  ANY_VALUE(`document_document`.`id`) as `id`,
        `document_document`.`document_id`,
        ANY_VALUE(`document_document`.`title`) as `title`,
        ANY_VALUE((
          SELECT COUNT(*)
          FROM `relation_relation`
          WHERE `relation_relation`.`document_id` = `document_document`.`id`
        )) as `relation_units`,
        COUNT(`view`.`id`) as `completions`,
        IF(SUM(`view`.`user_id` = {user_id}), true, false) as `user_completed`

FROM `document_document`

/* Link up the document group information for filtering purposes */
INNER JOIN `relation_relationgroup_documents`
    ON `relation_relationgroup_documents`.`document_id` = `document_document`.`id`
INNER JOIN `relation_relationgroup` as `group`
    ON `group`.`id` = `relation_relationgroup_documents`.`relationgroup_id`

 /* Link up the completed relationship views for each document
     A View is considered complete when all relationships have been submitted (requires 100%) */
INNER JOIN `document_section`
    ON `document_section`.`document_id` = `document_document`.`id`
LEFT JOIN `document_view` as `view`
    ON (`view`.`section_id` = `document_section`.`id` AND `view`.`task_type` = 'ri' AND `view`.`completed` = 1)

WHERE `group`.`enabled` = 1
GROUP BY `document_document`.`document_id`
/* Filter what we want to show on the dashboard */
HAVING  `relation_units` <= 20
    AND `completions` < {completions}
    AND `user_completed` = false
ORDER BY `completions` DESC
LIMIT 20
""".format(user_id=request.user.pk, completions=settings.ENTITY_RECOGNITION_K)
```

Taking only a `user_id` and the `completions` requirement,

- We're selecting document `pk`, `pmid`, and `title` directly from the document model.
- We're also selecting through a subquery, the number of relation tasks for a document (`relation_units`)
- We're also selecting through grouping joins the number of `total view completion`, and the boolean for if the `user_completed`

This is being done directly on the document table (`document_document`)

- We're inner joining in any document to relationship group relations so we **1)** only get documents that are part of a Relation Task Group (`relation_relationgroup`) and **2)** can only show the documents of these groups that are enabled later on with a filter
- We're also joining in the document section to reach the document's user views (`document_view`). We need this so we can see which views are considered complete to filtering with are completions threshold later on.

We're then filtering (`WHERE`) or post query filtering (`HAVING`) to select our uncompleted documents.

The change I'm suggesting largely addresses the use of the `document_view` join as the means to determine if a Document for a Relationship Task is completed and will instead use a `GROUP` on the `relation_relationannotation` table.

**Comment by x0xMaximus** [comment]
Not complete by any means, and this will require grouping on the document_id and relationship id to count Relation answers but this is a query going off the Relation annotations rather than views

![](http://i.imgur.com/xK5nAe3.png)

**Comment by andrewsu** [comment]
We think this issue is no longer occurring.
