### ISSUE TITLE
User scores not updating

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#207]
User reported that doing ER tasks not contributing to his score.

Confirmed this to be the case using GATTACA account.
![01 score before](https://cloud.githubusercontent.com/assets/9200138/20766585/d548e292-b6eb-11e6-9849-af7d8bb894d6.PNG)
Completed 1 relationship task which increased the total score by 75pts.
Next completed 1 ER task earning 1000pts
(It should not be 1000pts though because I'm the 3rd user to submit this doc)
![02 task completed](https://cloud.githubusercontent.com/assets/9200138/20766671/2a68fece-b6ec-11e6-8520-dfb9e17c1e0d.PNG)
Yet as seen here, the score has not changed. 
![03 score after](https://cloud.githubusercontent.com/assets/9200138/20766702/45a45b16-b6ec-11e6-9bc3-632494f7e50b.PNG)
Confirmed that this issue is not specific to abstracts with no entities to mark.

**Comment by andrewsu** [comment]
Likely related to my comment just added in #126 (https://github.com/SuLab/mark2cure/issues/126#issuecomment-274189747)

**Comment by gtsueng** [comment]
Report of problem from skye dated 2017.05.05:
"I wanted to report a problem with my account: every time I submit an Entry Recognition Task I get the screen which says "New Annotations! ...1000 points..." instead of the usual screen where I see my highlights matched with someone else's. The 1000 points is never added to my score (wouldn't that be a nice glitch!) but I do still get the 5000 at the end of the quest and it counts towards the overall number of people who have annotated that quest.

When I do the Document Relation Tasks there doesn't seem to be any problems and points are added to my total score correctly. I didn't log into my account for at least 6 months between September and March, so maybe that's a clue to the source of the problem."
