### ISSUE TITLE
Profile changes made by user cannot be saved

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#210]
Reproducible and give 500 error. 

This is the sentry error for it: https://sentry.io/su-lab/mark2cure_prod/issues/132963248/

**Comment by JTFouquier** [comment]
UserForm is an class imported from Django allauth and it doesn't have a .save() method. 

When settings are updated, data is saved to db.

<img width="564" alt="screen shot 2017-02-23 at 2 16 09 pm" src="https://cloud.githubusercontent.com/assets/7920357/23280014/ce99a7ac-f9d4-11e6-834b-41bac7535223.png">

<img width="532" alt="screen shot 2017-02-23 at 3 33 48 pm" src="https://cloud.githubusercontent.com/assets/7920357/23282241/93de3642-f9dd-11e6-9224-d82ce2baa895.png">
