### ISSUE TITLE
create team option broken

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#216]
Users cannot create a new team within Mark2Cure from the setting page.  Creating a new team via the admin panel works, but does not generate a public team page (url gives 500 error).

See this team page created when this function worked: https://mark2cure.org/team/tsri/
vs this team page created via the admin panel: https://mark2cure.org/team/sdpl/

**Comment by JTFouquier** [comment]
This is fixed by the above commit. You can create a team, and all the team profile pages work. Safe to pull on production.
