### ISSUE TITLE
login integration with Zooniverse

### ISSUE THREAD

**Issue by andrewsu** [SuLab/mark2cure#224]
By invitation of the Zooniverse team, let's integrate our login system with Zooniverse's.  Then they can/will feature us more prominently.  From the initial email:

> You should be able to use the panoptes-javascript-client oauth module to adopt the Zooniverse login into Mark2Cure. Module documentation and usage examples are provided here;
>  
> https://github.com/zooniverse/panoptes-javascript-client
>  
> https://zooniverse.github.io/panoptes-javascript-client/#panoptes-javascript-client-oauth
>  
> I have cc’d in Roger, who is the developer at the Zooniverse who wrote this module – please let us know if you have any questions about this process.

Don't want to drop roger's email in a public ticket, but I have it...

**Comment by x0xMaximus** [comment]
Just confirmed on production. Need to wrap up assigning levels after RE Training to get to the dashboard but that is unrelated to auth. Closing for now.
