### ISSUE TITLE
No access to talk pages from dashboard

### ISSUE THREAD

**Issue by gtsueng** [SuLab/mark2cure#232]
Seems like a space was left for it, so I'm guessing it just hasn't been turned back on
![image](https://user-images.githubusercontent.com/9200138/31677914-359b446e-b321-11e7-8711-86f2f3fc0238.png)

**Comment by x0xMaximus** [comment]
Unless otherwise discussed, Talk pages weren't understood as a priority with the updates. Rather than just "enable" – I will plan to have them rebuilt.
