### ISSUE TITLE
Cancel and return button in settings page

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#28]
If user accidentally makes changes they don't want to keep in the settings page, give them a way to cancel and return them to what they were doing. We don't want to get them in the habit of hitting the 'back' button in the browser, which is what they'll resort to.

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/28
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2014-12-04T19:40:40.298

**Comment by x0xMaximus** [comment]
@gtsueng A cancel button was added, which essentially is just a link back to the profile page. This lets people cancel and go back. Is this resolved now?

**Comment by x0xMaximus** [comment]
This hasn't been confirmed by @gtsueng but I just checked and my cancel button fulfills what this originally wanted.
