### ISSUE TITLE
Grouped ER Annotation Submission and status indication

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#29]
For slower connections, user is tempted to hit browser back button and to click all over the place after submitting a doc due to the lag between submit and feedback.

---
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/29
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2014-12-04T20:04:00.547

**Comment by JTFouquier** [comment]
Loading indication would be nice during quest loading too.  For slow/spotty connections, loading the quest can take awhile during which the user has no idea what's going on.

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by x0xMaximus** [comment]
This is slow b/c each annotation is submitted independently in the ER task. While a progress indicator would still be helpful, I suspect grouping it as a single API will reduce the majority of the time. 

I'm gracefully ignoring the quest loading icon as we handle that.
