### ISSUE TITLE
create staging environment

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#52]
for testing and evaluation, especially so we can use our test user accounts without polluting the production database.

---
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/52
- Originally reported by: [Andrew Su](http://bitbucket.org/asu)
- Originally created at: 2015-01-27T22:37:50.455

**Comment by JTFouquier** [comment]
@andrewsu I was able to make a new m2c dev instance from an AMI made from the m2c production instance. This new instance seemed "almost there" (ubuntu up and running in ssh) but when going to the public IP address, there is a redirect issue that brings you to the production version of the mark2cure.org website. Okay, so then I tried to make a new instance that was built up from scratch using ubuntu.  This one I am having issues even starting the instance (even though I did it in the same way as the first one but with starting with a "blank ubuntu").

I kind of put it out of my mind because I'm pretty confused because it seems like a lot of this needs to deviate from their standard tutorials. Should I get help from Cyrus? I know we still want this to happen!  Thanks!!

----------------------------------------
Original comment by: [Jennifer Fouquier](http://bitbucket.org/JTFouquier)

**Comment by x0xMaximus** [comment]
Some consideration points:

- Is this valuable with a 1 person (or sub 3 person, etc) development team?
- Is this going to mirror the same tasks as the current servers to ensure non ui facing code is equally as functional
- Is this going to have any data mirroring, and / or database clones. As with any staging environment, the staging server isn't complicated, data persistency and inconsistencies in the data will cause a lot of headaches  
- Is this getting at a bigger desire to have a public AMI or automated build process
