### ISSUE TITLE
add email addresses to /analysis/users/training/, lock down access to certain accounts

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#61]
Current output format:

```
#!javascript

user_pk,T1,T2,T3,E1_Q1,E2_Q2
1,False,False,False,False,False
2,True,True,True,False,True
3,True,False,False,False,False

```

Add a column for email addresses.  For privacy reasons, need to restrict access to /analysis/users/training/ to special users.

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/61
- Originally reported by: [Andrew Su](http://bitbucket.org/asu)
- Originally created at: 2015-02-02T18:10:28.424

**Comment by x0xMaximus** [comment]
After thinking about this, I'm going to propose this isn't ever implemented. From an analysis perspective, a user's email address isn't relevant to any of the analysis reports we need to do, their user_id, which is what's included are all that are required. Additionally, this issue will be overhauled anyway with the new control panel that serves #194 

If a users email address is desired for marketing purposes, those settings and preferences should be managed within our CRM / MailChimp
