### ISSUE TITLE
Handle back button

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#64]
either: 
a) disable it when they are in a quest
b) enable it, but when they go back - have it catch that they have already completed the task at that URL, thank them for completing it, tell them that they can't change their responses in the current version of the software, click ok, and send them back to where they came from.

From user: "I wanted to go “back” and check a previous review – so I hit the “back arrow.”  It did not take me back one but instead took me to the 1st review in the series.  It did not show my markings so since that did not help me answer my question, I hit the “forward arrow.”  It did not take me back to the 3rd or 4th one I was doing but instead brought me to the last review in the series."

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/64
- Originally reported by: [bgood](http://bitbucket.org/bgood)
- Originally created at: 2015-02-03T22:18:06.457

**Comment by JTFouquier** [comment]
**Ways of navigating out of a quest:**

1. Browser provided back button
1. Logo link (takes to dashboard)
1. Navigate away to settings page (in header)
1. Navigate away to flatpages (in footer)
1. Immediately signoff


**State of game while in quest:**

1. Reading / annotating
2. Reviewing annotations
3. Reviewing quest completion

Proposal **a** to disable is not technically feasible. However, more importantly it would result in frustration from being unable to navigate freely, while simultaneously forcing continuation of a quest (which may lead to annotations simply put for the purpose to exit the quest). Unclear on the details of **b**. Generally speaking, it causes a great deal of user frustration when you interrupt expected navigation behavior, any changes that are made to explain annotation persistence should be designed to alleviate that as much as possible. 

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by x0xMaximus** [comment]
@gtsueng Can we close this all together now? Given it's not appropriate for a site to disable navigational behavior, we've circumvented this issue by ensuring that the return to a quest does an reasonable job of inserting the user back into the appropriate place within a ER Quest or Relation Task Set.

**Comment by x0xMaximus** [comment]
Closes as it hasn't been addressed by @gtsueng since July and has been around since Feb 2015, we will not (and can't) alter the behavior of a browsers navigational buttons. Additionally, given the amount of AJAX work we're doing, is this no longer relevant. However, it was largely covered by the work I did that allows quests to be revisited while preserving the step state of the users contributions to that particular quest (or now relation task)
