### ISSUE TITLE
identify corpus of documents for NGLY1 experiment

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#80]
probably needs discussion between me and Ben...

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/80
- Originally reported by: [Andrew Su](http://bitbucket.org/asu)
- Originally created at: 2015-02-22T00:05:55.419

**Comment by JTFouquier** [comment]
https://docs.google.com/document/d/1M96FPKI63OpvaKCuPE6ApUv2DBDZuEXySJyR1HOi-qc/edit

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by x0xMaximus** [comment]
Unless further discussion is desired for additional groups we want to load in between @andrewsu and @goodb for new exploratory directions, this is no longer relevant
