### ISSUE TITLE
Grouped quest selection menu (Knowledge Map)

### ISSUE THREAD

**Issue by JTFouquier** [SuLab/mark2cure#89]
Create Knowledge Map, a graphical menu that allows users to pick out groups of quests of interest to them.  

Bin docs by field or subject, then group into quests and bin the quests into nodes.  Selecting nodes on the knowledge map will reveal the quests available under that node, which the user can work on.  We can limit groups of quests available by locking the 'nodes' on the map.

Mocked up here: 
https://docs.google.com/presentation/d/1HYZ9LcK9J9zykMgluDO990vXEioK-B5nm8I7PSSrb0c/edit?pli=1#slide=id.g75560fab3_022

----------------------------------------
- Bitbucket: https://bitbucket.org/sulab/mark2cure/issue/89
- Originally reported by: [gtsueng](http://bitbucket.org/gtsueng)
- Originally created at: 2015-03-19T16:16:01.204

**Comment by JTFouquier** [comment]
Another design idea (Andrew's preferred) - Display the grouped quests like photos in Google+.  Loose mock up also in the aforementioned google slide.


----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by JTFouquier** [comment]
![5-14-2015 11-41-54 AM.jpg](https://bitbucket.org/repo/y7oq9p/images/440905920-5-14-2015%2011-41-54%20AM.jpg)

----------------------------------------
Original comment by: [Andrew Su](http://bitbucket.org/asu)

**Comment by JTFouquier** [comment]
Until more design work is done or we think about how exactly this should be implemented, this is complete development wise.

----------------------------------------
Original comment by: [Max Nanis](http://bitbucket.org/x0xMaximus)

**Comment by JTFouquier** [comment]
Expand quest groupings ala google photo library

----------------------------------------
Original comment by: [gtsueng](http://bitbucket.org/gtsueng)

**Comment by x0xMaximus** [comment]
I'm suggesting this gets closed as we're lessening emphasis on ER and have taken the approach that we'll guide users through work to do. If we want to create a more exploratory design to the dashboard, this discussion will come up again during that phase

**Comment by x0xMaximus** [comment]
Also, worth noting this is someone addressed in #194 and how we organize new documents that will get imported
